project:
  type: website
  output-dir: docs

website:
  title: "Brian"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Project"
        href: fyp.qmd
      - text: "Data Visualization"
        href: datavis.qmd
      - text: "Reflection"
        href: reflection.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


